syntax = "proto3";
package api.v1;

// Different ticket status
enum Status {
  STATUS_UNSPECIFIED = 0;
  STATUS_OPEN        = 1;
  STATUS_IN_PROGRESS = 2;
  STATUS_RESOLVED    = 3;
  STATUS_CLOSED      = 4;
}

// Object Ticket
message Ticket {
  int64  id          = 1;
  string title       = 2;
  string description = 3;
  Status status      = 4;
  string created_at  = 5;
  string updated_at  = 6;
}

// Create Ticket
message CreateTicketRequest {
  string title       = 1;
  string description = 2;
}

message CreateTicketResponse {
  Ticket ticket = 1;
}

// Get Ticket
message GetTicketRequest {
  int64 id = 1;
}

message GetTicketResponse {
  Ticket ticket = 1;
}

// Delete Ticket
message DeleteTicketRequest {
  int64 id = 1;
}

message DeleteTicketResponse {}

// Get all tickets
message GetAllTicketRequest {}

message GetAllTicketResponse {
  repeated Ticket ticket = 1;
}

// Service
service TicketService {
  rpc CreateTicket(CreateTicketRequest)  returns (CreateTicketResponse) {}
  rpc GetTicket(GetTicketRequest)        returns (GetTicketResponse)    {}
  rpc GetAllTickets(GetAllTicketRequest) returns (GetAllTicketResponse) {}
  rpc DeleteTicket(DeleteTicketRequest)  returns (DeleteTicketResponse) {}
}